# 配置端口
server:
  port:8802
# 数据源
spring:
  datasource:
    diver-class-name:com.mysql.jdbc.Driver
    url:jdbc:mysql://localhost:3306/mysql?useUnicode=true&characterEncoding=UTF-8
    username:iseeu
    password:root
    type:com.alibaba.druid.pool.DruidDataSource
  jpa:
    show-sql:true

# mybaties-plus
mybaties-plus:
  mapper-locations:classpath: mapper/*Mapper.xml